directories:
  output: release
  buildResources: build
appId: com.example.passwordmanager
productName: Password Manager
files:
  - filter:
      - '**/*'
      - '!node_modules/.bin'
      - '!node_modules/electron'
      - '!node_modules/electron-builder'
      - '!node_modules/electron-reload'
      - '!release/'
win:
  target: nsis
  icon: build/icon.ico
mac:
  category: your.app.category
  identity: null
  hardenedRuntime: false
  entitlements: null
  forceCodeSigning: false
  target: dmg
  icon: build/icon.icns
linux:
  target: AppImage
  icon: build/icon.png
electronVersion: 34.5.8
