name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [20.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      # Крок для збірки macOS: запускається ТІЛЬКИ на macOS-раннері
      - name: Build Electron App (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run dist -- --mac # Використовуйте тільки --mac тут

      # Крок для збірки Windows: запускається ТІЛЬКИ на Windows-раннері
      - name: Build Electron App (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run dist -- --win # Використовуйте тільки --win тут

      # Крок для збірки Linux: запускається ТІЛЬКИ на Ubuntu (Linux)-раннері
      - name: Build Electron App (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist -- --linux # Використовуйте тільки --linux тут

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build-artifacts
          path: release/